version: '3.7'

services:
  web:
    build: ./Django
    command: python manage.py runserver 0.0.0.0:8910 --noreload
    volumes:
      - ./Django/:/usr/src/app/
    ports:
      - "8910:8910"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5431:5432"

  demo:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app/demo
    ports:
      - "8000:8000"
      - "35729:35729"


volumes:
  postgres_data: